// Knight: melee spear-fighter whose own speed is the resource it's managing. It accelerates
// for as long as it goes without landing a hit, and the spear's damage scales directly with
// however fast it's currently going — 5 at the 200 floor speed, +1 per 30 px/s on top, up to
// 15 at the hard 500 speed ceiling. Landing a hit recoils it backward and drops it to the floor,
// so every thrust cashes in the momentum it built and starts the climb over. It never slows
// down to stay near its target, so at high speed it blows straight past and comes back around.
//
// The ultimate is a single devastating charge: it summons a horse, starts from a higher floor
// (400), accelerates faster, damage scales twice as steeply (+2 per 30 px/s), and — critically
// — there is no speed ceiling and no time limit while mounted. It just keeps winding up until
// it finally connects, and that one thrust ends the ultimate. The longer the horse takes to
// land the hit, the more brutal the hit is.

const KNIGHT_MAX_HP = 150;

const KNIGHT_BASE_SPEED = 200;      // speed floor — what it's knocked back to right after landing a hit
const KNIGHT_MAX_SPEED  = 700;      // hard speed ceiling while un-mounted (so 22 damage at full wind-up)
// At the old 30/s the Knight only reached ~320 speed within one 4s cooldown, so its 500 ceiling
// was unreachable and the damage-scales-with-speed mechanic never actually paid out. 55/s puts
// the ceiling in reach of a long chase, which is where the whole design's payoff lives.
const KNIGHT_SPEED_RAMP_RATE = 55;  // px/s gained per second un-mounted (200 -> 700 in ~9s)

const KNIGHT_ATTACK_DAMAGE_BASE = 5;  // damage dealt at exactly the un-mounted floor speed (200)
const KNIGHT_DAMAGE_SPEED_STEP  = 30; // every 30 px/s above that floor adds damage...
const KNIGHT_DAMAGE_PER_STEP    = 1;  // ...this much of it un-mounted, so 200 speed = 5 damage and 500 speed = 15, the un-mounted max
const KNIGHT_ATTACK_COOLDOWN   = 4.0;  // seconds between spear thrusts
const KNIGHT_ATTACK_RANGE      = 65;   // reach beyond body contact, on top of both characters' own radii (placeholder, tune later)
const KNIGHT_ATTACK_ANIM_TIME  = 0.2;  // spear-thrust animation length

const KNIGHT_ULTIMATE_CHARGE_TIME   = 15.0; // seconds to fill the meter
const KNIGHT_DAMAGE_CHARGE_BONUS    = 0.1;  // seconds shaved off that charge per point of damage dealt
const KNIGHT_MOUNTED_MIN_SPEED      = 400;  // speed floor the charge starts from
const KNIGHT_MOUNTED_SPEED_RAMP_RATE = 40;  // px/s gained per second while mounted — uncapped, it never stops climbing
const KNIGHT_MOUNTED_DAMAGE_PER_STEP = 2;   // mounted, each 30 px/s step is worth double

const KNIGHT_VICTORY_CHARGE_SPEED = 850; // px/sec of the mounted victory gallop off-screen

// Pre-drawn art (see web/assets, generated by tools/make_knight_art.py). Both sprites are
// drawn pointing/facing +x, so they only need rotating to the Knight's facing angle.
// anchorX/anchorY are the pivot as a fraction of the sprite's own size: the spear's grip,
// and the horse's saddle seat — which is where the Knight's body lands, so the horse hangs
// off it correctly rather than being centered on it.
function makeKnightArt(src, displayWidth, anchorX, anchorY) {
  const img = new Image();
  img.src = src;
  return { img, displayWidth, anchorX, anchorY };
}

const KNIGHT_SPEAR_ART = makeKnightArt("assets/knight_spear.png?v=1", 100, 0.143, 0.5);
// Held out far enough that the vamplate (the cone hand-guard) lands on the body's rim rather
// than buried in the middle of it, which puts the blade tip right about at the attack range.
const KNIGHT_SPEAR_FORWARD_OFFSET = 16;
// How the lance rides while it's on cooldown: swung up off the line of attack (negative =
// away from the horse, which sits below the rider) and drawn back toward the body.
const KNIGHT_SPEAR_STOW_SWING    = -1.15; // radians at full stow
const KNIGHT_SPEAR_STOW_PULLBACK = 22;    // px pulled back at full stow

// The moment the lance finishes coming back down and is live again gets its own flourish:
// it kicks forward, the blade lights up, and sparks fly off the tip.
const KNIGHT_SPEAR_READY_FLASH_TIME = 0.45; // seconds the ready flourish lasts
const KNIGHT_SPEAR_READY_SNAP = 12;         // px of forward kick as it snaps into position
const KNIGHT_HORSE_ART = makeKnightArt("assets/knight_horse.png?v=1", 190, 0.462, 0.342);

class Knight extends Character {
  constructor(x, y) {
    super({
      x, y,
      size: CHAR_BASE_SIZE,
      color: "#7a8494",
      maxHp: KNIGHT_MAX_HP,
      name: "Knight",
      speed: KNIGHT_BASE_SPEED,
    });

    this.facingAngle = Math.random() * Math.PI * 2;
    this.attackTimer = 0;
    this.attackAnimTimer = 0; // >0 briefly right after a thrust, for the lunge animation
    this.inRange = false;     // whether the opponent is within spear range right now

    this.speedRampTimer = 0; // seconds since the last hit (or mount/dismount) — drives the speed ramp

    this.skillState = "charging"; // charging | mounted
    this.chargeTime = 0; // seconds charged so far while charging; seconds remaining while mounted

    this.spearRaise = 0; // smoothed 0..1: 0 = lance stowed back, 1 = couched and ready to thrust
    this.spearReadyFlashTimer = 0; // >0 during the "lance is live again" flourish
    this.spearWasReady = false;    // edge-detects that moment so it only fires once per cooldown

    this.celebrating = false; // true once it's won: keeps trotting around, spear held high
  }

  // Victory lap: summons the horse and gallops flat out toward whichever side of the arena
  // it's furthest from, so the run across the screen is as long as possible before it exits.
  onVictory() {
    this.celebrating = true;
    this.skillState = "mounted";
    this.chargeTime = 0;

    const dir = this.x > ARENA.x + ARENA.w / 2 ? -1 : 1;
    this.facingAngle = dir > 0 ? 0 : Math.PI;
    this.speed = KNIGHT_VICTORY_CHARGE_SPEED;
    this.vx = dir * KNIGHT_VICTORY_CHARGE_SPEED;
    this.vy = 0;
    this.knockbackVx = 0;
    this.knockbackVy = 0;
    this.spearRaise = 1; // lance couched for the charge
    this.spearReadyFlashTimer = 0;
    playSfx("knightHorse", 0.7);
  }

  get mounted() {
    return this.skillState === "mounted";
  }

  // Where the lance *should* be right now: stowed while it can't attack, then rising back to
  // couched as the cooldown burns off. Squared so it stays down through most of the wait and
  // comes up sharply at the end, which telegraphs the incoming thrust.
  get spearReadiness() {
    if (!this.canAttack || this.stunTimer > 0) return 0;
    const t = Math.max(0, Math.min(1, 1 - this.attackTimer / KNIGHT_ATTACK_COOLDOWN));
    return t * t;
  }

  // Where the lance's point currently is in world space, following both the stow swing and
  // the pullback. The swing is applied after the mirror in drawSprite, so mirrored facings
  // need it negated to land in the same place on screen.
  get spearTipPoint() {
    const stowed = 1 - this.spearRaise;
    const dist = KNIGHT_SPEAR_FORWARD_OFFSET - stowed * KNIGHT_SPEAR_STOW_PULLBACK
      + (1 - KNIGHT_SPEAR_ART.anchorX) * KNIGHT_SPEAR_ART.displayWidth;
    const flip = Math.cos(this.facingAngle) < 0 ? -1 : 1;
    const angle = this.facingAngle + flip * stowed * KNIGHT_SPEAR_STOW_SWING;
    return { x: this.x + Math.cos(angle) * dist, y: this.y + Math.sin(angle) * dist };
  }

  get attackRange() {
    return this.size / 2 + KNIGHT_ATTACK_RANGE;
  }

  // Damage is a deterministic function of current speed, not a random roll: 5 at the floor
  // speed, plus one step's worth per 30 px/s on top. Un-mounted that's +1 per step against a
  // 500 speed ceiling, so it runs 5 -> 15; mounted it's +2 per step against no ceiling at
  // all, so the payout is unbounded and grows the longer the charge takes to connect.
  get attackDamage() {
    const excess = Math.max(0, this.speed - KNIGHT_BASE_SPEED);
    const perStep = this.mounted ? KNIGHT_MOUNTED_DAMAGE_PER_STEP : KNIGHT_DAMAGE_PER_STEP;
    return Math.round(KNIGHT_ATTACK_DAMAGE_BASE + (excess / KNIGHT_DAMAGE_SPEED_STEP) * perStep);
  }

  // this.speed alone doesn't retroactively rescale an already-moving vx/vy (those only ever
  // get set from it at spawn, off a wall bounce, or coming out of a stun) — so every frame,
  // this rescales the CURRENT velocity to whatever speed the ramp says it should be right
  // now, preserving whatever direction it's already heading in.
  updateSpeedRamp(dt) {
    this.speedRampTimer += dt;
    const floorSpeed = this.mounted ? KNIGHT_MOUNTED_MIN_SPEED : KNIGHT_BASE_SPEED;
    const rampRate = this.mounted ? KNIGHT_MOUNTED_SPEED_RAMP_RATE : KNIGHT_SPEED_RAMP_RATE;
    // Un-mounted the climb stops dead at 500. Mounted there's no ceiling at all — the charge
    // just keeps winding up until it connects, which is the whole point of the ultimate.
    let targetSpeed = floorSpeed + rampRate * this.speedRampTimer;
    if (!this.mounted) targetSpeed = Math.min(targetSpeed, KNIGHT_MAX_SPEED);
    this.speed = targetSpeed;

    const mag = Math.hypot(this.vx, this.vy);
    if (mag > 0.01) {
      const scale = targetSpeed / mag;
      this.vx *= scale;
      this.vy *= scale;
    }
  }

  update(dt, opponent) {
    if (this.deathFadeTimer > 0) this.deathFadeTimer -= dt; // keeps fading even though the rest of update() bails out below
    if (!this.alive) return;

    // Eased toward the target rather than snapped, so the lance drops away fast after a hit
    // and sweeps back up smoothly instead of popping between poses.
    this.spearRaise += (this.spearReadiness - this.spearRaise) * Math.min(1, dt * 8);
    if (this.spearReadyFlashTimer > 0) this.spearReadyFlashTimer -= dt;

    // The instant the lance goes live again — sound, sparks, and the flourish below.
    const spearReady = this.canAttack && this.stunTimer <= 0 && this.attackTimer <= 0 && !this.celebrating;
    if (spearReady && !this.spearWasReady) {
      this.spearReadyFlashTimer = KNIGHT_SPEAR_READY_FLASH_TIME;
      playSfx("knightSpearReady", 0.5);
      const tip = this.spearTipPoint;
      spawnImpactParticles(tip.x, tip.y, ["#fff2c0", "#ffd070", "#ffffff"], 14, 1.1, 0);
      spawnFlash(tip.x, tip.y, "#ffe0a0", 48, 0.25);
    }
    this.spearWasReady = spearReady;

    // Deliberately not super.update() — that would bounce it off the arena walls, and the
    // whole point is that it rides straight out of frame and doesn't come back.
    if (this.celebrating) {
      this.x += this.vx * dt;
      this.y += this.vy * dt;
      return;
    }

    if (opponent && opponent.alive) {
      const dx = opponent.x - this.x;
      const dy = opponent.y - this.y;
      const dist = Math.hypot(dx, dy);
      if (dist > 0.01) this.facingAngle = Math.atan2(dy, dx);
      this.inRange = dist <= this.attackRange + opponent.size / 2;
    } else {
      this.inRange = false;
    }

    this.updateSpeedRamp(dt);
    super.update(dt, opponent);
    if (this.stunTimer > 0) return; // dazed — can't attack or charge up right now

    if (this.attackAnimTimer > 0) this.attackAnimTimer -= dt;

    // Mounting has no timer to run down: the charge ends when it lands its one thrust, which
    // is handled in the attack block below. So only the charging state ticks here.
    if (this.skillState === "charging") {
      this.chargeTime += dt;
      if (this.chargeTime >= KNIGHT_ULTIMATE_CHARGE_TIME) {
        this.skillState = "mounted";
        this.chargeTime = 0;
        // Mounting must never cost speed: 400 is a floor to be lifted to, not a value to snap
        // to. Seeding the ramp timer with however far the current speed already is past that
        // floor keeps whatever it had built up, then carries on climbing from there.
        this.speedRampTimer = Math.max(0, this.speed - KNIGHT_MOUNTED_MIN_SPEED) / KNIGHT_MOUNTED_SPEED_RAMP_RATE;
        playSfx("knightHorse", 0.7);
        spawnImpactParticles(this.x, this.y, ["#c8a050", "#8a5a20", "#ffffff"], 30, 1.4, -30);
        spawnFlash(this.x, this.y, "#ffe0a0", 90, 0.4);
        triggerShake(6, 0.25);
      }
    }

    if (this.attackTimer > 0) this.attackTimer -= dt;

    if (opponent && opponent.alive && this.attackTimer <= 0 && this.inRange && this.canAttack) {
      const dmg = this.attackDamage; // read while still mounted, and before the recoil resets this.speed
      const wasMounted = this.mounted;
      opponent.takeDamage(dmg);
      this.attackTimer += KNIGHT_ATTACK_COOLDOWN;
      this.attackAnimTimer = KNIGHT_ATTACK_ANIM_TIME;

      // The mounted charge is a one-shot: connecting with it is what ends the ultimate.
      if (wasMounted) {
        this.skillState = "charging";
        spawnImpactParticles(this.x, this.y, ["#c8a050", "#8a5a20", "#ffffff"], 24, 1.3, -20);
        triggerShake(7, 0.3);
      }

      // Bounces backward off the target, landing back at the un-mounted floor speed — cashing
      // in whatever momentum it had built, as a physical recoil rather than a silent in-place
      // magnitude change. (After a mounted hit it has just dismounted, so this is 200 too.)
      this.speedRampTimer = 0;
      this.speed = KNIGHT_BASE_SPEED;
      this.vx = -Math.cos(this.facingAngle) * KNIGHT_BASE_SPEED;
      this.vy = -Math.sin(this.facingAngle) * KNIGHT_BASE_SPEED;

      // Every point of damage dealt — the ultimate's own thrust included — shaves 0.1s off
      // the next charge.
      this.chargeTime += dmg * KNIGHT_DAMAGE_CHARGE_BONUS;

      playSfx("knightSpearHit", 0.9);

      const impactX = opponent.x - Math.cos(this.facingAngle) * (opponent.size / 2);
      const impactY = opponent.y - Math.sin(this.facingAngle) * (opponent.size / 2);
      spawnImpactParticles(impactX, impactY, ["#cccccc", "#8a94a8", "#ffffff"], 14, 1, 0);
    }
  }

  // Both sprites are drawn from their anchor, rotated to face the target. Past straight-up
  // and straight-down the rotation alone would leave them upside down, so they get mirrored
  // across their own long axis — which keeps the horse's legs below it and the spear's
  // pennant above it no matter which way the Knight is heading.
  drawSprite(ctx, art, forwardOffset = 0, swing = 0) {
    const img = art.img;
    if (!img.complete || img.naturalWidth === 0) return;

    const dw = art.displayWidth;
    const dh = dw * (img.naturalHeight / img.naturalWidth);
    ctx.save();
    ctx.translate(this.x, this.y);
    ctx.rotate(this.facingAngle);
    if (Math.cos(this.facingAngle) < 0) ctx.scale(1, -1);
    if (swing) ctx.rotate(swing); // after the mirror, so it swings the same visual way both ways
    if (forwardOffset) ctx.translate(forwardOffset, 0);
    ctx.drawImage(img, -art.anchorX * dw, -art.anchorY * dh, dw, dh);
    ctx.restore();
  }

  // The horse, anchored at its saddle so the Knight's body sits in the seat.
  drawHorse(ctx) {
    this.drawSprite(ctx, KNIGHT_HORSE_ART);
  }

  // The lance, anchored at its grip, thrusting forward briefly on a hit. Between thrusts it
  // rides stowed — swung up off the line of attack and pulled back toward the body — and
  // lowers into the couched position again as the cooldown runs out.
  drawSpear(ctx) {
    const lungeT = this.attackAnimTimer > 0
      ? Math.sin((1 - this.attackAnimTimer / KNIGHT_ATTACK_ANIM_TIME) * Math.PI)
      : 0;
    const stowed = 1 - this.spearRaise;
    // Kicks forward and eases back as it snaps into the couched position.
    const snap = this.spearReadyFlashTimer > 0
      ? Math.sin((this.spearReadyFlashTimer / KNIGHT_SPEAR_READY_FLASH_TIME) * Math.PI) * KNIGHT_SPEAR_READY_SNAP
      : 0;
    const forward = KNIGHT_SPEAR_FORWARD_OFFSET - stowed * KNIGHT_SPEAR_STOW_PULLBACK + lungeT * 16 + snap;
    this.drawSprite(ctx, KNIGHT_SPEAR_ART, forward, stowed * KNIGHT_SPEAR_STOW_SWING);
    this.drawSpearReadyGlow(ctx);
  }

  // The blade lighting up the moment it becomes live again — a hot streak down the shaft and
  // an expanding ring off the point, both fading out over the flourish.
  drawSpearReadyGlow(ctx) {
    if (this.spearReadyFlashTimer <= 0 || !this.alive) return;

    const t = this.spearReadyFlashTimer / KNIGHT_SPEAR_READY_FLASH_TIME; // 1 -> 0
    const tip = this.spearTipPoint;
    const gripX = this.x + Math.cos(this.facingAngle) * (this.size / 2);
    const gripY = this.y + Math.sin(this.facingAngle) * (this.size / 2);

    ctx.save();
    ctx.globalCompositeOperation = "lighter";

    ctx.globalAlpha = t * 0.85;
    ctx.strokeStyle = "#ffe9a8";
    ctx.lineWidth = 2 + t * 6;
    ctx.lineCap = "round";
    ctx.beginPath();
    ctx.moveTo(gripX, gripY);
    ctx.lineTo(tip.x, tip.y);
    ctx.stroke();

    const r = 10 + (1 - t) * 26;
    const grad = ctx.createRadialGradient(tip.x, tip.y, 0, tip.x, tip.y, r);
    grad.addColorStop(0, "rgba(255,255,255,0.95)");
    grad.addColorStop(0.45, "rgba(255,214,120,0.5)");
    grad.addColorStop(1, "rgba(255,190,80,0)");
    ctx.globalAlpha = t;
    ctx.fillStyle = grad;
    ctx.beginPath();
    ctx.arc(tip.x, tip.y, r, 0, Math.PI * 2);
    ctx.fill();

    ctx.globalAlpha = t * 0.8;
    ctx.strokeStyle = "#fff0c0";
    ctx.lineWidth = 2.5;
    ctx.beginPath();
    ctx.arc(tip.x, tip.y, 8 + (1 - t) * 34, 0, Math.PI * 2);
    ctx.stroke();

    ctx.restore();
  }

  // Round body, a closed-visor helmet, and a small crest — the spear is drawn separately
  // (on top) so its lunge animation isn't clipped by the body draw order.
  drawBody(ctx) {
    const s = this.size;

    if (this.mounted) this.drawHorse(ctx);

    ctx.save();
    ctx.translate(this.x, this.y);

    ctx.fillStyle = this.color;
    ctx.beginPath();
    ctx.arc(0, 0, s / 2, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = "rgba(0,0,0,0.35)";
    ctx.lineWidth = 2.5;
    ctx.stroke();

    ctx.fillStyle = "rgba(255,255,255,0.14)";
    ctx.beginPath();
    ctx.arc(-s * 0.15, -s * 0.15, s * 0.16, 0, Math.PI * 2);
    ctx.fill();

    // Closed-visor helmet: a plain dome plus a dark horizontal slit instead of round eyes.
    ctx.fillStyle = "#5a6272";
    ctx.beginPath();
    ctx.arc(0, -s * 0.05, s * 0.44, Math.PI, Math.PI * 2);
    ctx.closePath();
    ctx.fill();
    ctx.strokeStyle = "rgba(0,0,0,0.3)";
    ctx.lineWidth = 1.5;
    ctx.stroke();

    ctx.fillStyle = "#1a1c22";
    ctx.fillRect(-s * 0.22, -s * 0.12, s * 0.44, s * 0.07);

    // Small crest/plume on top, colored gold while mounted (matches the horse's tack).
    ctx.fillStyle = this.mounted ? "#e0b040" : "#b03030";
    ctx.beginPath();
    ctx.moveTo(0, -s * 0.48);
    ctx.quadraticCurveTo(s * 0.14, -s * 0.7, s * 0.04, -s * 0.85);
    ctx.quadraticCurveTo(-s * 0.06, -s * 0.68, 0, -s * 0.48);
    ctx.fill();

    ctx.restore();

    this.drawSpear(ctx);
  }

  // Mounted has no countdown of its own — the charge lasts until it connects — so the bar
  // just holds full while mounted rather than disappearing.
  get ultimateRatio() {
    if (this.mounted) return 1;
    return Math.min(1, this.chargeTime / KNIGHT_ULTIMATE_CHARGE_TIME);
  }

  get ultimateBarColor() {
    return "#e0b040";
  }

  // No drawHud override: the HUD is deliberately just name + HP bar + ultimate bar for every
  // character. The ability/cooldown readouts that used to sit under it are gone.
}
